version: 2
project_name: kubectl-ctx-diff

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: .
    binary: kubectl-ctx-diff
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/salvador-arreola/kubectl-ctx-diff/cmd.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: salvador-arreola
    name: kubectl-ctx-diff
  draft: false
  prerelease: auto
