apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: ctx-diff
spec:
  version: v0.2.2
  homepage: https://github.com/salvador-arreola/kubectl-ctx-diff
  shortDescription: Diff k8s resources between two contexts
  description: |
    Compare Kubernetes environments across kubeconfig contexts.
    Diffs any namespaced resource including CRDs, with colored
    table or JSON output. Secret values are never exposed.

    Usage:
      kubectl ctx-diff diff --context-2 prod -n my-namespace
      kubectl ctx-diff diff --context-2 prod --filter configmaps,secrets
      kubectl ctx-diff diff --context-2 prod -o json

  platforms:
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      uri: https://github.com/salvador-arreola/kubectl-ctx-diff/releases/download/v0.2.2/kubectl-ctx-diff_linux_amd64.tar.gz
      sha256: "df5df01598cb5886ace992787c7311999a19335eb2804ce5a24b33403df3dee2"
      bin: kubectl-ctx-diff
      files:
        - from: kubectl-ctx-diff
          to: .
        - from: LICENSE
          to: .

    - selector:
        matchLabels:
          os: linux
          arch: arm64
      uri: https://github.com/salvador-arreola/kubectl-ctx-diff/releases/download/v0.2.2/kubectl-ctx-diff_linux_arm64.tar.gz
      sha256: "2fd1f39ed2b2666f1a242563121d7d31ced9cfa690a593d6e498aff31f60029c"
      bin: kubectl-ctx-diff
      files:
        - from: kubectl-ctx-diff
          to: .
        - from: LICENSE
          to: .

    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      uri: https://github.com/salvador-arreola/kubectl-ctx-diff/releases/download/v0.2.2/kubectl-ctx-diff_darwin_amd64.tar.gz
      sha256: "e0b2768929c2259ca9a52cfba77e92b2e4d13a74788dc6c7341e716ad2bf9107"
      bin: kubectl-ctx-diff
      files:
        - from: kubectl-ctx-diff
          to: .
        - from: LICENSE
          to: .

    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      uri: https://github.com/salvador-arreola/kubectl-ctx-diff/releases/download/v0.2.2/kubectl-ctx-diff_darwin_arm64.tar.gz
      sha256: "a2a7a86aaeb1722c7ee0b69757d6e6c6488c071adbb99e9508f2a7617cbeb9c6"
      bin: kubectl-ctx-diff
      files:
        - from: kubectl-ctx-diff
          to: .
        - from: LICENSE
          to: .

    - selector:
        matchLabels:
          os: windows
          arch: amd64
      uri: https://github.com/salvador-arreola/kubectl-ctx-diff/releases/download/v0.2.2/kubectl-ctx-diff_windows_amd64.zip
      sha256: "3808dca6846ac26fa29b1deb62e5cfc5ee87ad3d03814849963e6df17782236f"
      bin: kubectl-ctx-diff.exe
      files:
        - from: kubectl-ctx-diff.exe
          to: .
        - from: LICENSE
          to: .
